# Generated by Django 6.0.6 on 2026-07-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='sub_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
