# Generated by Django 6.0.6 on 2026-07-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_exam_status_exam_sub_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='seconds',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_duration',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='type_name',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
