# Generated by Django 6.0.6 on 2026-07-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_remove_exam_minutes_remove_exam_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=500)),
                ('bharti', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=500)),
                ('dec', models.CharField(max_length=500)),
            ],
        ),
    ]
