# Generated by Django 6.0.6 on 2026-07-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_student_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_description', models.TextField(blank=True, null=True)),
                ('total_questions', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('marks', models.CharField(max_length=50)),
                ('exam_instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available Now'), ('upcoming', 'Upcoming'), ('closed', 'Closed')], default='upcoming', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='AvailExamInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MyExampage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_description', models.TextField(blank=True, null=True)),
                ('total_questions', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('marks', models.CharField(max_length=50)),
                ('exam_instructions', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
