# Generated by Django 6.0.6 on 2026-07-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_availableexam_availexaminstruction_examinstruction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_full_name', models.CharField(max_length=200)),
                ('teacher_email', models.EmailField(max_length=254, unique=True)),
                ('teacher_password', models.CharField(max_length=255)),
                ('teacher_address', models.TextField()),
                ('teacher_profile', models.ImageField(upload_to='teacher/images/')),
                ('teacher_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('teacher_dob', models.DateField()),
                ('teacher_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
