# Generated by Django 6.0.6 on 2026-07-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
