# Generated by Django 6.0.6 on 2026-07-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_teacher_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('academy_logo', models.ImageField(blank=True, null=True, upload_to='academy/logo/')),
                ('academy_banner', models.ImageField(blank=True, null=True, upload_to='academy/banner/')),
                ('website', models.URLField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='status',
        ),
    ]
