# Generated by Django 6.0.6 on 2026-07-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_academy_remove_teacher_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='academy_banner',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/academy/banner/'),
        ),
        migrations.AlterField(
            model_name='academy',
            name='academy_logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/academy/logo/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_profile',
            field=models.ImageField(upload_to='static/images/teacher/images/'),
        ),
    ]
