# Generated by Django 6.0.6 on 2026-07-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_adminprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='static/images/profile/images/'),
            preserve_default=False,
        ),
    ]
