# Generated by Django 6.0.6 on 2026-07-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingregistration',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
