# Generated by Django 6.0.6 on 2026-07-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_pendingregistration_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
