# Generated by Django 6.0.6 on 2026-07-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_registration_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='static/student/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
        migrations.AlterField(
            model_name='registration',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
