# Generated by Django 6.0.6 on 2026-07-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_registration_remove_registration_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student/'),
        ),
    ]
