# Generated by Django 6.0.6 on 2026-07-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_registration_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_registration',
        ),
    ]
