# Generated by Django 6.0.6 on 2026-07-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_delete_student_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/srudent/images/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/srudent/images/'),
        ),
    ]
