# Generated by Django 6.0.6 on 2026-07-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_pendingregistration_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student/images/'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student/images/'),
        ),
    ]
